export const Images = {
  Logo: require("./logo.png"),
  Menu: require("./menu.png"),
  Background: require("./background.png"),
  Download: require("./download.png"),
  Favorites: require("./favorites.png"),
  Recents: require("./recents.png"),
  Routine: require("./routine.png"),
  RightArrow: require("./rightArrow.png"),
  DonationBackground: require("./donationBackground.png"),
  QuotesBackground: require("./quotesBackground.png"),
  QuotesIcon: require("./quotesIcon.png"),
  Kids1: require("./kids1.png"),
  Kids2: require("./kids2.png"),
};
